pipeline {
   agent any
    
   tools{
        
         dockerTool 'docker'
    }

   stages{
   
           stage("Checkout code") {
            steps {
                checkout scm
                
            }
        }   
      
          stage("Build image") {
            steps {
                script {
                    myapp = docker.build("mdshafi/sampledockerapp:${env.BUILD_ID}")
                }
            }
        }
      
      
            stage("Push image") {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                            myapp.push("latest")
                            //myapp.push("${env.BUILD_ID}")
                    }
                }
            }
          }
        
      
      
      
      
   }   
}
