pipeline {
   agent any
    
   tools{
        
         dockerTool 'docker'
    }

    stage('Clone repository') {
        /* Cloning the Repository to our Workspace */

        checkout scm
       }
    

   
}
